# Generated by Django 2.2.6 on 2019-10-26 01:13

import colorfield.fields
from django.db import migrations, models
import pay.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20191021_1251'),
        ('form', '0002_auto_20191021_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='gateway',
        ),
        migrations.AddField(
            model_name='form',
            name='background_color',
            field=colorfield.fields.ColorField(default='#327F8F', max_length=18),
        ),
        migrations.AddField(
            model_name='form',
            name='gateways',
            field=models.ManyToManyField(blank=True, related_name='form_gateway', to='gateway.Gateway'),
        ),
        migrations.AddField(
            model_name='form',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='form',
            name='random',
            field=models.CharField(default=pay.utils.generate_random, max_length=6),
        ),
        migrations.AddField(
            model_name='form',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
