# Generated by Django 2.2.6 on 2019-10-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20191026_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='note',
        ),
        migrations.AddField(
            model_name='form',
            name='note_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('optional', 'Optional'), ('required', 'Required')], default='disabled', max_length=20),
        ),
    ]
