# Generated by Django 2.2.6 on 2019-10-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20191026_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
