# Generated by Django 2.2.6 on 2019-10-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('irr', 'IRR'), ('usd', 'USD'), ('eur', 'EUR'), ('btc', 'BTC')], default='irr', max_length=5),
        ),
    ]
