# Generated by Django 2.2.6 on 2019-10-25 03:40

from django.db import migrations, models
import pay.utils


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20191021_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='random',
            field=models.CharField(default=pay.utils.generate_random, max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('rejected', 'Rejected')], max_length=30),
        ),
    ]
