# Generated by Django 2.2.6 on 2019-11-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
