# Generated by Django 2.2.6 on 2019-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
